---
- name: Check if PostgreSQL is already installed
  ansible.builtin.stat:
    path: "/usr/{{ (postgres_type == 'PG')|ternary('pgsql-', 'edb/as') }}{{ postgres_version.split('.')|first }}/bin/pg_ctl"
  register: postgres_installed

- name: stop postgres
  args:
    removes: "/usr/{{ (postgres_type == 'PG')|ternary('pgsql-', 'edb/as') }}{{ postgres_version.split('.')|first }}/bin/pg_ctl"
  shell: "/usr/{{ (postgres_type == 'PG')|ternary('pgsql-', 'edb/as') }}{{ postgres_version.split('.')|first }}/bin/pg_ctl stop -D {{ postgres_folders.data_dir }}"
  ignore_errors: yes
  become_user: "{{ postgres_user }}"
  when: postgres_installed.stat.exists

- name: Attendre que PostgreSQL soit stoppé
  wait_for:
    path: "/tmp/.s.PGSQL.{{ postgres_port }}"
    state: absent
    timeout: 60
  become: yes
  become_user: "{{ postgres_user }}"


