---
- name: Retrieve running services
  service_facts:

- name: Record pgpool services states
  set_fact:
    pgpool_service_state: "{{ (ansible_facts.services['pgpool.service']|d({'state': 'down'})).state }}"

- name: stop pgpool
  systemd:
    name: pgpool
    state: stopped
  when: pgpool_service_state != 'down'