#! /bin/sh
# Online recovery 2nd stage script
#
DATADIR=$1      # master dabatase cluster
DEST=$2         # hostname of the DB node to be recovered
DESTDIR=$3      # database cluster of the DB node to be recovered
PORT=$4         # PostgreSQL port number

PGHOME=/usr/{{ (postgres_type == 'PG')|ternary('pgsql-', 'edb/as') }}{{ postgres_version.split('.')|first }}
ARCHIVEDIR={{ postgres_folders.backup_dir }}

# Force to flush current value of sequences to xlog 
${PGHOME}/bin/psql -p $PORT -t -c 'SELECT datname FROM pg_database WHERE NOT datistemplate AND datallowconn' template1|
while read i
do
  if [ "$i" != "" ]; then
    psql -p $PORT -c "SELECT setval(oid, nextval(oid)) FROM pg_class WHERE relkind = 'S'" $i
  fi
done

psql -p $PORT -c "SELECT pgpool_switch_xlog('$ARCHIVEDIR')" template1
